### ISSUE TITLE
After tethering, all hummingbirds respawn at the same point, momentarially overlapping.

### ISSUE THREAD

**Issue by thitchings14** [Streus/Time-Is-Not#18] opened 2018-02-13 15:41 UTC

**Comment by Streus** [comment] 2018-02-13 23:10
This is very difficult to reproduce consistently.  A possible fix has been made, but there's no definitive way to tell.

**Comment by thitchings14** [comment] 2018-02-15 14:55
Pulled latest version and is currently still broken. Should we ask around and see if its a per-device issue? Cause if so we will have a hard time fixing it for everyone?

**Comment by thitchings14** [comment] 2018-02-15 15:20
Not sure if you know, but part of the issue may be related to  the Patrolnodes, as all hummingbirds default to the first linked set of nodes instead of their patrolstart setting after tether.

**Comment by thitchings14** [comment] 2018-02-15 16:36
Hummingbirds seem to randomly respawn at another's position and adopt it's routes. Will attempt to test it more to find out more.

**Comment by Streus** [comment] 2018-02-21 18:08
It is worth noting that it has been found that this is not a problem exclusive to Hummingbirds.  It seems to be an issue with RegisteredObjects, specifically with their ID generation and storage in a hash table.

A fix to the generation problems is possible.  As for the possible hashing problem, either a change to a our data structure or a change to our ID generation method is needed.

**Comment by dmatias94** [comment] 2018-02-24 23:47
So I was having some issues with when I would die by a death laser, I would use the Time Tether ability which would reset Margaux near "Manual" doors that open when the player walks near them automatically. My issue is that after tethering and walking towards these doors, another instance of these doors is created on top of the original door that was in the scene. I think it also might have something to do with the registered object script.

**Comment by Streus** [comment] 2018-03-01 00:44
Finally putting this issue to rest.


Good riddance.

**Closed by Streus** 2018-03-01 00:44 UTC
Labels: bug, urgent
